name: Sync Fork

on:
  schedule:
    - cron: '*/60 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: CrowdStrike
          repo: ember-headless-form
          base: main
          head: upstream
